'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ValidationsMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PresentasionWindowsForms.ValidationsMessages", GetType(ValidationsMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El campo no puede estar vacío.
        '''</summary>
        Friend Shared ReadOnly Property EMPTY_FIELD() As String
            Get
                Return ResourceManager.GetString("EMPTY_FIELD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Correo de ejemplo: ejemplo@dominio.|com|ac.cr|es|etc...
        '''</summary>
        Friend Shared ReadOnly Property INVALID_EMAIL() As String
            Get
                Return ResourceManager.GetString("INVALID_EMAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Minimos 8 caracteres númericos..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_PHONE_NUMBER() As String
            Get
                Return ResourceManager.GetString("INVALID_PHONE_NUMBER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Minimos 9 caracteres númericos.(Formato con ceros).
        '''</summary>
        Friend Shared ReadOnly Property INVALID_USER_ID() As String
            Get
                Return ResourceManager.GetString("INVALID_USER_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Solo se puede ingresar texto y espacios.(No puede estar vacio).
        '''</summary>
        Friend Shared ReadOnly Property ONLY_TEXT_ALLOW_SPACES() As String
            Get
                Return ResourceManager.GetString("ONLY_TEXT_ALLOW_SPACES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La contraseña debe de tener al menos 8 caracteres, una letra mayuscula, una minuscula y al menos un número..
        '''</summary>
        Friend Shared ReadOnly Property PASSWORD_INCORRECT_FORMAT() As String
            Get
                Return ResourceManager.GetString("PASSWORD_INCORRECT_FORMAT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
